# Generated by Django 4.0.4 on 2022-05-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], default='Team', max_length=30),
        ),
        migrations.AddField(
            model_name='registration',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
            preserve_default=False,
        ),
    ]
